GUI/JukeBox-ASP/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JukeBox;
using Microsoft.AspNetCore.Mvc;

namespace JukeBox_ASP.Controllers {
    public class AlbumController : Controller {
        public AlbumController(IConnection connection) {
            this.connection = connection;
        }

        [Route("[controller]/{id:long}")]
        public async Task<IActionResult> Get(ulong id) {
            var album = await connection.AlbumByIdAsync(id);
            return View(album);
        }

        private IConnection connection;
    }
}

GUI/JukeBox-ASP/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JukeBox;
using JukeBox_ASP.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace JukeBox_ASP.Controllers {
    public class GenreController : Controller {
        public GenreController(IConnection connection) {
            this.connection = connection;
        }

        [Route("[controller]")]
        public IActionResult All() {
            return RedirectToAction("Get", new { id = 1 });
        }

        [Route("[controller]/{id:long}")]
        public async Task<IActionResult> Get(ulong id, string type = "performers", int page = 1) {
            ViewBag.Id = id;
            ViewBag.Page = page;
            ViewBag.PerPage = 20;
            ViewBag.Type = type;

            if (Request.IsAjaxRequest()) {
                return PartialView("_Get");
            }

            var genres = await connection.AllGenresAsync();
            return View(genres);
        }

        private IConnection connection;
    }
}

GUI/JukeBox-ASP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using JukeBox_ASP.Extensions;
using Microsoft.AspNetCore.Mvc;
using JukeBox;

namespace JukeBox_ASP.Controllers {
    public class HomeController : Controller {
        public HomeController(IConnection connection) {
            this.connection = connection;
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult About() {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public IActionResult Contact() {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public IActionResult Error() {
            return View();
        }

        public IActionResult Link(string key) {
            return ViewComponent("Link", new { key = key });
        }

        public async Task<IActionResult> Search(string text, string type, int page = 1) {
            if (type != null && type != "performers" && type != "albums" && type != "tracks") {
                return NotFound();
            }
            if (string.IsNullOrWhiteSpace(text)) {
                text = string.Empty;
            }

            ViewBag.Text = text;
            ViewBag.Type = type;
            ViewBag.Page = page;
            ViewBag.PerPage = 20;

            if (Request.IsAjaxRequest()) {
                switch (type) {
                case "performers":
                    return PartialView("_Performers", await connection.SearchPerformersAsync(text));
                case "albums":
                    return PartialView("_Albums", await connection.SearchAlbumsAsync(text));
                case "tracks":
                    return PartialView("_Tracks", await connection.SearchTracksAsync(text));
                default:
                    break;
                }
            }

            return View(await connection.SearchAllAsync(text));
        }

        private IConnection connection;
    }
}

GUI/JukeBox-ASP/Controllers/PerformerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JukeBox;
using Microsoft.AspNetCore.Mvc;

namespace JukeBox_ASP.Controllers {
    public class PerformerController : Controller {
        public PerformerController(IConnection connection) {
            this.connection = connection;
        }

        [Route("[controller]/{id:long}")]
        public async Task<IActionResult> Get(ulong id) {
            Performer performer = await connection.PerformerByIdAsync(id);
            if (performer == null) {
                return NotFound();
            }

            return View(performer);
        }

        private IConnection connection;
    }
}

GUI/JukeBox-ASP/ViewComponents/AlbumViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JukeBox;
using Microsoft.AspNetCore.Mvc;

namespace JukeBox_ASP.ViewComponents {
    public class AlbumViewComponent : ViewComponent {
        public AlbumViewComponent(IConnection connection) {
            this.connection = connection;
        }

        public async Task<IViewComponentResult> InvokeAsync(ulong id) {
            var performer = await connection.PerformerByIdAsync(id);
            var albums = performer.Albums;

            return View(albums);
        }

        private IConnection connection;
    }
}

GUI/JukeBox-ASP/ViewComponents/AlbumsViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JukeBox;
using Microsoft.AspNetCore.Mvc;

namespace JukeBox_ASP.Views.Shared.Components.Albums {
    public class AlbumsViewComponent : ViewComponent {

        public IViewComponentResult Invoke(IEnumerable<Album> albums, int page, int size) {
            return View(albums.Skip((page - 1) * size).Take(size));
        }
    }
}

GUI/JukeBox-ASP/ViewComponents/AllViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JukeBox;
using Microsoft.AspNetCore.Mvc;

namespace JukeBox_ASP.ViewComponents {
    public class AllViewComponent : ViewComponent {
        public IViewComponentResult Invoke(Objects model) {
            return View(model);
        }
    }
}

GUI/JukeBox-ASP/ViewComponents/GenreViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JukeBox;
using Microsoft.AspNetCore.Mvc;

namespace JukeBox_ASP.ViewComponents {
    public class GenreViewComponent : ViewComponent {
        public GenreViewComponent(IConnection connection) {
            this.connection = connection;
        }

        public async Task<IViewComponentResult> InvokeAsync(ulong id, string type) {
            var genre = new Genre(id);

            switch (type) {
            case "performers":
                var performers = await connection.PerformersByGenreAsync(genre);
                return View("Performers", performers);
            case "albums":
                var albums = await connection.AlbumsByGenreAsync(genre);
                return View("Albums", albums);
            case "tracks":
                return View("Tracks", await connection.TracksByGenreAsync(genre));
            default:
                break;
            }

            return null;
        }

        private IConnection connection;
    }
}

GUI/JukeBox-ASP/ViewComponents/LinkViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JukeBox;
using Microsoft.AspNetCore.Mvc;

namespace JukeBox_ASP.ViewComponents {
    public class LinkViewComponent : ViewComponent {
        public LinkViewComponent(IConnection connection) {
            this.connection = connection;
        }

        public async Task<IViewComponentResult> InvokeAsync(string key) {
            return Content(await connection.LinkByKeyAsync(key));
        }

        private IConnection connection;
    }
}

GUI/JukeBox-ASP/ViewComponents/PerformersViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JukeBox;
using Microsoft.AspNetCore.Mvc;

namespace JukeBox_ASP.ViewComponents {
    public class PerformersViewComponent : ViewComponent {
        public IViewComponentResult Invoke(IEnumerable<Performer> performers, int page, int size) {
            return View(performers.Skip((page - 1) * size).Take(size));
        }
    }
}

GUI/JukeBox-ASP/ViewComponents/TracksViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JukeBox;
using Microsoft.AspNetCore.Mvc;

namespace JukeBox_ASP.ViewComponents {
    public class TracksViewComponent : ViewComponent {
        public IViewComponentResult Invoke(IEnumerable<Track> tracks, int page, int size) {
            return View(tracks.Skip((page - 1) * size).Take(size));
        }
    }
}

GUI/JukeBox-ASP/Views/Album/Get.cshtml
@model Album

@{
    ViewBag.Title = Model.Name;
}

<div class="page-album">
    <div class="page-album__head">
        <img class="album-cover album-cover_size_L" src="@await Component.InvokeAsync("Link", new { key = Model.Photo })" />
        <div class="stamp">
            <span class="stamp__title">Альбом</span>
        </div>
        <div class="page-album__title">
            <h1>@Model.Name</h1>
        </div>
        <div class="album-summary">
            <span class="album-summary__item">Исполнитель:</span>
            <span>@Model.Performer.Name</span>
            <div class="album-summary__group album-summary__item">
                @Model.Date.Year
                <span class="separator"></span>
                @await Html.PartialAsync("_Genres", Model.Genres)
            </div>
        </div>
    </div>
    <hr />
    <div class="page-album__tracks">
        @foreach (var track in Model.Tracks) {
            <div class="performer__track">
                <button type="button" class="btn btn-s button__play" style="margin-right: 15px; margin-left: 13px" data-key="@track.Key" data-state="pause">
                    <i class="glyphicon glyphicon-play" style="color: black"></i>
                </button>
                <span>
                    <a asp-controller="track" asp-action="get" asp-route-id="@track.Id" class="link">
                        @track.Name
                    </a>
                </span>
                <span style="color: #999; margin-right: 5px; margin-left: 5px">-</span>
                <span style="color: #999">
                    <a asp-controller="performer" asp-action="get" asp-route-id="@Model.Performer.Id" class="link link_mute">
                        @Model.Performer.Name
                    </a>
                </span>
            </div>
        }
    </div>
    <hr />
    <div class="page-performer__subhead">
        <div class="title">
            <span class="title__label">Все альбомы исполнителя</span>
        </div>
    </div>
    <div style="margin-left: -22px">
        @await Component.InvokeAsync("Album", new { id = Model.Performer.Id })
    </div>
</div>

GUI/JukeBox-ASP/Views/Genre/Get.cshtml
@model IEnumerable<Genre>

@{
    ViewBag.Title = "Музыка всех жанров";
}

<div class="nav__subnav" style="display: block;">
    @foreach (var genre in Model) {
        <div class="nav__sub-item">
            <a asp-controller="genre" asp-action="get" asp-route-id="@genre.Id" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#genre-content"
               data-ajax-success="onGenreChanged" class="button @if (ViewBag.Id == genre.Id) { <text>button_checked</text> }">
                <span class="button__label">@genre.Name</span>
            </a>
        </div>
    }
</div>

<div id="genre-content">
    @await Html.PartialAsync("_Get")
</div>


@section scripts {
    <script type="text/javascript">
        function onGenreChanged() {
            $(".nav__subnav").find(".button_checked").removeClass("button_checked");
            $(this).addClass("button_checked");
        }
    </script>
}

GUI/JukeBox-ASP/Views/Genre/_Get.cshtml
<div class="page-genre">
    <div class="tabs">
        <div id="tab-performers" class="tabs__tab @if (ViewBag.Type == "performers") { <text>tabs__tab_current</text> }">
            <a asp-controller="genre" asp-action="get" asp-route-id="@ViewBag.Id" asp-route-type="performers"
               data-ajax="true" data-ajax-mode="replace" data-ajax-update="#genre-content" class="link">Исполнители</a>
        </div>
        <div id="tab-albums" class="tabs__tab @if (ViewBag.Type == "albums") { <text>tabs__tab_current</text> }">
            <a asp-controller="genre" asp-action="get" asp-route-id="@ViewBag.Id" asp-route-type="albums"
               data-ajax="true" data-ajax-mode="replace" data-ajax-update="#genre-content" class="link">Альбомы</a>
        </div>
        <div id="tab-tracks" class="tabs__tab @if (ViewBag.Type == "tracks") { <text>tabs__tab_current</text> }">
            <a asp-controller="genre" asp-action="get" asp-route-id="@ViewBag.Id" asp-route-type="tracks"
               data-ajax="true" data-ajax-mode="replace" data-ajax-update="#genre-content" data-ajax-success="handle" class="link">Треки</a>
        </div>
    </div>
</div>

@await Component.InvokeAsync("Genre", new { id = ViewBag.Id, type = ViewBag.Type })

GUI/JukeBox-ASP/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GUI/JukeBox-ASP/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Title</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GUI/JukeBox-ASP/Views/Home/Search.cshtml
@model Objects

@{
    ViewBag.Title = "Search Page";
    var performers = Model.Performers;
    var albums = Model.Albums;
    var tracks = Model.Tracks;
}

<ul class="nav nav-pills" style="margin-bottom:16px">
    <li class="active">
        <a href="#cs-ajax-all" data-toggle="pill">Всё</a>
    </li>
    <li id="performers_pill">
        <a href="#cs-ajax-performers" data-toggle="pill">Исполнители - @performers.Count()</a>
    </li>
    <li id="albums_pill">
        <a href="#cs-ajax-albums" data-toggle="pill">Альбомы - @albums.Count()</a>
    </li>
    <li id="tracks_pill">
        <a href="#cs-ajax-tracks" data-toggle="pill">Треки - @tracks.Count()</a>
    </li>
</ul>

<div class="tab-content">
    <div id="cs-ajax-all" class="tab-pane fade in active">
        @await Component.InvokeAsync("All", new { model = Model })
    </div>
    <div id="cs-ajax-performers" class="tab-pane fade">
        @await Html.PartialAsync("_Performers", performers);
    </div>
    <div id="cs-ajax-albums" class="tab-pane fade">
        @await Html.PartialAsync("_Albums", albums);
    </div>
    <div id="cs-ajax-tracks" class="tab-pane fade">
        @await Html.PartialAsync("_Tracks", tracks);
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        var observer = new MutationObserver(function (mutations) {
            mutations.some(function (mutation) {
                if ($(mutation.target).hasClass("in")) {
                    console.log(mutation.target);
                    console.log(mutation.type);
                    var buttons = $(mutation.target).find(".button__play");
                    helper(buttons);
                    return true;
                }
            });
        });

        observer.observe($("#cs-ajax-tracks")[0], {
            attributes: true
        });
        observer.observe($("#cs-ajax-all")[0], {
            attributes: true
        });

        $("#tracks_link,#albums_link,#performers_link").click(function () {
            $(".nav-pills").find(".active").removeClass("active");
            $($(this).attr("data-pill-id")).addClass("active");
        });
    </script>
}

GUI/JukeBox-ASP/Views/Home/_Albums.cshtml
@model IEnumerable<Album>

@await Component.InvokeAsync("Albums", new { albums = Model, page = ViewBag.Page, size = ViewBag.PerPage })

<div class="text-center">
    <cs-pager cs-pagenumber-param="page" cs-paging-pagenumber="@ViewBag.Page" cs-paging-pagesize="@ViewBag.PerPage"
              cs-paging-totalitems="@Model.Count()" cs-paging-maxpageritems="4" cs-ajax-target="#cs-ajax-albums"
              asp-controller="home" asp-action="search" asp-route-text="@ViewBag.Text" asp-route-type="albums"></cs-pager>
</div>

GUI/JukeBox-ASP/Views/Home/_Performers.cshtml
@model IEnumerable<Performer>

<div class="panel-body">
    @await Component.InvokeAsync("Performers", new { performers = Model, page = ViewBag.Page, size = ViewBag.PerPage })
</div>

<div class="text-center">
    <cs-pager cs-pagenumber-param="page" cs-paging-pagenumber="@ViewBag.Page" cs-paging-pagesize="@ViewBag.PerPage"
              cs-paging-totalitems="@Model.Count()" cs-paging-maxpageritems="4" cs-ajax-target="#cs-ajax-performers"
              asp-controller="home" asp-action="search" asp-route-text="@ViewBag.Text" asp-route-type="performers"></cs-pager>
</div>

GUI/JukeBox-ASP/Views/Home/_Tracks.cshtml
@model IEnumerable<Track>

@await Component.InvokeAsync("Tracks", new { tracks = Model, page = ViewBag.Page, size = ViewBag.PerPage })

<div class="text-center">
    <cs-pager cs-pagenumber-param="page" cs-paging-pagenumber="@ViewBag.Page" cs-paging-pagesize="@ViewBag.PerPage"
              cs-paging-totalitems="@Model.Count()" cs-paging-maxpageritems="4" cs-ajax-target="#cs-ajax-tracks" cs-ajax-success="handle"
              asp-controller="home" asp-action="search" asp-route-text="@ViewBag.Text" asp-route-type="tracks"></cs-pager>
</div>

GUI/JukeBox-ASP/Views/Performer/Get.cshtml
@model Performer

@{
    ViewBag.Title = Model.Name;
}

<div>
    <div class="page-performer">
        <div class="performer-pics">
            <img class="performer-pics__pic" src="@await Component.InvokeAsync("Link", new { key = Model.Photo })" />
        </div>
        <div class="page-performer__info">
            <div class="stamp">
                <span class="stamp__title">Исполнитель</span>
            </div>
            <h1 class="page-performer__title">@Model.Name</h1>
            <div class="page-performer__summary">@await Html.PartialAsync("_Genres", Model.Genres)</div>
            <div class="page-performer__desc">@Model.Description</div>
        </div>
        <div class="page-performer__tabs">
            <div class="tabs">
                <div class="tabs__tab tabs__tab_current">
                    <a data-toggle="tab" href="#tracks" class="link">Треки</a>
                </div>
                <div class="tabs__tab">
                    <a data-toggle="tab" href="#albums" class="link">Альбомы</a>
                </div>
            </div>
        </div>
        <div class="tab-content">
            <div id="tracks" class="tab-pane fade in active">
                <div class="page-performer__subhead">
                    <div class="title">
                        <span class="title__label">Треки</span>
                    </div>
                </div>
                <div class="page-performer__tracks">
                    <div class="table-head" style="color: #999">
                        <span style="position: absolute; left: 1.4%">#</span>
                        <span class="" style="position: absolute; left:10%">Название трека</span>
                        <span class="" style="position: absolute; left:40%">Альбом</span>
                    </div>
                    <div>
                        <div style="position: relative">
                            @{
                                foreach (var track in Model.Tracks) {
                                    <div class="performer__track">
                                        <button type="button" class="btn btn-s button__play" data-key="@track.Key" data-state="pause">
                                            <i class="glyphicon glyphicon-play" style="color: black"></i>
                                        </button>
                                        <span style="position: absolute; left: 10%">
                                            <a asp-controller="track" asp-action="get" asp-route-id="@track.Id" class="link">
                                                @track.Name
                                            </a>
                                        </span>
                                        <span style="position: absolute; left: 40%">
                                            <a asp-controller="album" asp-action="get" asp-route-id="@track.Album.Id" class="link link_mute">
                                                @track.Album.Name
                                            </a>
                                        </span>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div id="albums" class="tab-pane fade">
                <div class="page-performer__subhead">
                    <div class="title">
                        <span class="title__label">Альбомы</span>
                    </div>
                </div>
                <div style="margin-left: -22px">
                    @await Component.InvokeAsync("Albums", new { albums = Model.Albums, page = 1, size = Model.Albums.Count() })
                </div>
            </div>
        </div>
    </div>
</div>

GUI/JukeBox-ASP/Views/Shared/Components/Album/Default.cshtml
@model IEnumerable<Album>

@await Component.InvokeAsync("Albums", new { albums = Model, page = 1, size = Model.Count() })

GUI/JukeBox-ASP/Views/Shared/Components/Albums/Default.cshtml
@model IEnumerable<Album>

@foreach (var album in Model) {
    var photo = await Component.InvokeAsync("Link", new { key = album.Photo });

    <div class="album">
        <img class="album__cover" src="@photo" />
        <div class="album__title">
            <a asp-controller="album" asp-action="get" asp-route-id="@album.Id" class="link">@album.Name</a>
        </div>
        <div class="album__performer">
            <a asp-controller="performer" asp-action="get" asp-route-id="@album.Performer.Id" class="link">@album.Performer.Name</a>
        </div>
        <div class="album__year">@album.Date.Year</div>
    </div>
}

GUI/JukeBox-ASP/Views/Shared/Components/All/Default.cshtml
@model Objects

<div class="panel panel-default" style="width:100%;">
    <div class="panel-heading">
        <span>Треки</span>
        <a id="tracks_link" data-toggle="pill" href="#cs-ajax-tracks" class="link" data-pill-id="#tracks_pill" style="float:right">Все треки</a>
    </div>
    @await Component.InvokeAsync("Tracks", new { tracks = Model.Tracks, page = 1, size = 7 })
</div>

<div class="panel panel-default" style="width:100%;">
    <div class="panel-heading">
        <span>Исполнители</span>
        <a id="performers_link" data-toggle="pill" href="#cs-ajax-performers" class="link" data-pill-id="#performers_pill" style="float:right">Все исполнители</a>
    </div>
    <div class="panel-body">
        @await Component.InvokeAsync("Performers", new { performers = Model.Performers, page = 1, size = 6 })
    </div>
</div>

<div class="panel panel-default" style="width:100%;">
    <div class="panel-heading">
        <span>Альбомы</span>
        <a id="albums_link" data-toggle="pill" href="#cs-ajax-albums" class="link" data-pill-id="#albums_pill" style="float:right">Все альбомы</a>
    </div>
    <div class="panel-body">
        @await Component.InvokeAsync("Albums", new { albums = Model.Albums, page = 1, size = 12 })
    </div>
</div>

GUI/JukeBox-ASP/Views/Shared/Components/Genre/Albums.cshtml
@model IEnumerable<Album>

@await Component.InvokeAsync("Albums", new { albums = Model, page = ViewBag.Page, size = ViewBag.PerPage })

<div class="text-center">
    <cs-pager cs-pagenumber-param="page" cs-paging-pagenumber="@ViewBag.Page" cs-paging-pagesize="@ViewBag.PerPage"
              cs-paging-totalitems="@Model.Count()" cs-paging-maxpageritems="4" cs-ajax-target="#genre-content"
              asp-controller="genre" asp-action="get" asp-route-id="@ViewBag.Id" asp-route-type="albums"></cs-pager>
</div>

GUI/JukeBox-ASP/Views/Shared/Components/Genre/Performers.cshtml
@model IEnumerable<Performer>

<div class="panel-body">
    @await Component.InvokeAsync("Performers", new { performers = Model, page = ViewBag.Page, size = ViewBag.PerPage })
</div>

<div class="text-center">
    <cs-pager cs-pagenumber-param="page" cs-paging-pagenumber="@ViewBag.Page" cs-paging-pagesize="@ViewBag.PerPage"
              cs-paging-totalitems="@Model.Count()" cs-paging-maxpageritems="4" cs-ajax-target="#genre-content"
              asp-controller="genre"
              asp-action="get" asp-route-id="@ViewBag.Id" asp-route-type="performers"></cs-pager>
</div>

GUI/JukeBox-ASP/Views/Shared/Components/Genre/Tracks.cshtml
@model IEnumerable<Track>

@await Component.InvokeAsync("Tracks", new { tracks = Model, page = ViewBag.Page, size = ViewBag.PerPage })

<div class="text-center">
    <cs-pager cs-pagenumber-param="page" cs-paging-pagenumber="@ViewBag.Page" cs-paging-pagesize="@ViewBag.PerPage"
              cs-paging-totalitems="@Model.Count()" cs-paging-maxpageritems="4" cs-ajax-target="#genre-content" cs-ajax-success="handle"
              asp-controller="genre" asp-action="get" asp-route-id="@ViewBag.Id" asp-route-type="tracks"></cs-pager>
</div>

GUI/JukeBox-ASP/Views/Shared/Components/Tracks/Default.cshtml
@model IEnumerable<Track>

<ul class="list-group">
    @foreach (var track in Model) {
    var photo = await Component.InvokeAsync("Link", new { key = track.Album.Photo });

    <li class="list-group-item track">
        <div class="track__cover">
            <img class="track__album-cover img-circle" src="@photo" />
        </div>
        <div class="track__name">
            <a asp-controller="track" asp-action="get" asp-route-id="@track.Id" class="track__title link">@track.Name</a>
            <div class="track__performer">
                <a asp-controller="performer" asp-action="get" asp-route-id="@track.Performer.Id" class="link">@track.Performer.Name</a>
            </div>
        </div>
        <div class="play__section">
            <button type="button" class="btn btn-lg button__play" data-key="@track.Key" data-state="pause">
                <i class="glyphicon glyphicon-play" style="color: black"></i>
            </button>
        </div>
    </li>
    }
</ul>

GUI/JukeBox-ASP/Views/Shared/_Genres.cshtml
@model IEnumerable<Genre>

@foreach (var genre in Model) {
    <a asp-controller="genre" asp-action="get" asp-route-id="@genre.Id" title="@genre.Name" class="link link_mute">@genre.Name</a>
}